name: Deploy Client PWA to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'client-pwa/**'
      - '.github/workflows/deploy-client.yml'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: housescanner-client
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ubuntu

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client-pwa
          file: ./client-pwa/Dockerfile.prod
          platforms: linux/amd64
          push: true
          build-args: |
            VITE_API_URL=http://${{ env.EC2_HOST }}:3000/api/v1
            VITE_WS_URL=http://${{ env.EC2_HOST }}:3000
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Build Summary
        run: |
          echo "✅ Docker Image Built Successfully!"
          echo "📦 Image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}"
          echo "🏷️  Tags: latest, ${{ steps.vars.outputs.sha_short }}"

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/housescanner
            
            echo "🔄 Pulling latest image..."
            docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            
            echo "🚀 Restarting client service..."
            docker compose -f docker-compose.prod.yml up -d --no-deps --build client
            
            echo "⏳ Waiting for health check..."
            timeout 60 sh -c 'until docker inspect --format="{{.State.Health.Status}}" housescanner-client-1 | grep -q "healthy"; do sleep 2; done' || echo "⚠️  Health check timeout (service may still be starting)"
            
            echo ""
            echo "==================================="
            echo "📊 Container Status:"
            docker ps --filter name=housescanner-client-1 --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
            
            echo ""
            echo "==================================="
            echo "📋 Recent Container Logs:"
            docker logs --tail 20 housescanner-client-1
            
            echo ""
            echo "🧹 Cleaning up old images..."
            docker image prune -f

      - name: Deployment Summary
        run: |
          echo "🎉 Client PWA Deployment Complete!"
          echo "📦 Image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.sha_short }}"
          echo "🌐 Application: http://${{ env.EC2_HOST }}:8080"
          echo "🏷️  Commit: ${{ github.sha }}"
